spring:
  application:
    name: question-service
  datasource:
    url: jdbc:postgresql://localhost:5433/questiondb
    username: postgres
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres
  cloud:
    function:
      definition: generateQuestionSet
    stream:
      bindings:
        generateQuestionSet-in-0:
          destination: add-new-quiz
          group: ${spring.application.name}
        notifyQuestionSetGenerated-out-0:
          destination: question-set-generated
      kafka:
        binder:
          brokers:
            - localhost:9092
h2:
  console:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/