spring:
  application:
    name: quiz-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quizdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  sql:
    init:
      mode: always
      platform: postgres
  cloud:
    function:
      definition: updateQuizQuestions
    stream:
      bindings:
        notifyAddNewQuiz-out-0:
          destination: ADD-NEW-QUIZ
        updateQuizQuestions-in-0:
          destination: QUESTION-SET-GENERATED
      kafka:
        binder:
          brokers:
            - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}

eureka:
  instance:
    preferIpAddress: ${eureka.instance.preferIpAddress:true}
  client:
    fetchRegistry: ${eureka.client.fetchRegistry:true}
    registerWithEureka: ${eureka.client.registerWithEureka:true}
    serviceUrl:
      # Docker Network: Uses service name from environment (e.g., from eureka.client.serviceUrl.defaultZone in docker-compose)
      defaultZone: ${eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/}

h2:
  console:
    enabled: true

server:
  port: 8090